spring:
  application:
    name: url-shortener
  profiles:
    default: dev
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener_db
    username: user
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        envers:
          audit_table_suffix: _AUD
          revision_field_name: rev
          revision_type_field_name: rev_type
          store_data_at_delete: true
          default_schema: public
  security:
    user:
      name: user
      password: ish1234
      roles: USER

server:
  address: localhost
  port: 8080

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,httptrace,loggers
  endpoint:
    health:
      show-details: always
  auditevents:
    enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [traceId=%X{traceId},spanId=%X{spanId}]"
  level:
    com.immortals.urlshortner.service: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema.internal.SchemaCreatorImpl: TRACE

cache:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    command-timeout: 2s
    use-ssl: false
    pool-max-total: 16
    pool-max-idle: 16
    pool-min-idle: 4
    pool-max-wait: 1s
    auto-reconnect: true
    enabled: true

auth:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "https://yourdomain.com"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      - "OPTIONS"
    allowed-headers:
      - "*"
    allow-credentials: true
    max-age: 3600

swagger:
    title: "URL Shortener API"
    description: "API for shortening URLs using different strategies."
    version: "1.0.0"
    terms-of-service: "https://example.com/terms"
    contact: "Support Team - support@example.com (https://example.com/support)"
    license:
      name: "Apache 2.0"
      url: "https://www.apache.org/licenses/LICENSE-2.0.html"
    servers:
      - url: "https://api.example.com"
      - description: "Production Server"
      - url: "http://localhost:8080"
      - description: "Local Dev Server"
    enabled: true