spring:
  application:
    name: url-shortener
  profiles:
    default: dev
    active: dev
  liquibase:
    default-schema: public
    liquibase-schema: public
    change-log: db/changelog-master.xml
    enabled: true
    url: jdbc:postgresql://localhost:5432/mini_url_db
    user: user
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        envers:
          audit_table_suffix: _AUD
          revision_field_name: rev
          revision_type_field_name: rev_type
          store_data_at_delete: true
          default_schema: public
  security:
    user:
      name: user
      password: ish1234
      roles: USER

server:
  address: localhost
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024 # in bytes



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    metadata-map:
      zone: primary
    hostname: ${HOSTNAME:localhost}

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  auditevents:
    enabled: true
  tracing:
    enabled: true
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

logging:
  pattern:
    level: "%5p [traceId=%X{traceId},spanId=%X{spanId}]"
  level:
    com.immortals.urlshortner.service: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.tool.schema.internal.SchemaCreatorImpl: TRACE

cache:
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
    command-timeout: 2s
    use-ssl: false
    pool-max-total: 16
    pool-max-idle: 16
    pool-min-idle: 4
    pool-max-wait: 1s
    auto-reconnect: true
    enabled: true

auth:
  cache:
    static-resources:
      max-age-seconds: 31536000
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "https://yourdomain.com"
    allowed-methods:
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
      - "OPTIONS"
    allowed-headers:
      - "*"
    allow-credentials: true
    max-age: 31536000

datasource:
  write:
    url: jdbc:postgresql://localhost:5432/mini_url_db
    username: user
    password: admin
    driver-class-name: org.postgresql.Driver
  read:
    url: jdbc:postgresql://localhost:5432/url_shortener_db
    username: user
    password: admin
    driver-class-name: org.postgresql.Driver