name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_IMAGE_NAME: mini-url
  DOCKER_REGISTRY: localhost:5000

jobs:
  setup:
    name: Environment Setup
    runs-on: ubuntu-latest
    outputs:
      java-version: 21

    steps:
      - name: ☕ Set up Java 21
        id: java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

  checkout-and-cache:
    name: Checkout & Cache
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 💾 Cache Gradle Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: 📦 Make Gradle wrapper executable
        run: chmod +x ./gradlew

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    needs: checkout-and-cache

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🛠️ Build Project
        run: ./gradlew clean build --no-daemon

      - name: ✅ Run Tests
        run: ./gradlew test --no-daemon

  sonar:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 📊 Run SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./gradlew sonarqube \
            -Dsonar.projectKey=mini-url \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🐳 Build Docker Image
        run: |
          docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest .

      - name: 📤 Push Docker Image to Local Registry
        run: |
          docker tag $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest
          docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest