openapi: 3.0.3
info:
  title: URL Shortener API
  description: API for shortening and redirecting URLs with advanced options
  version: 1.0.0

servers:
  - url: https://api.yourdomain.com/api/v1
    description: Production server

tags:
  - name: URL Shortener
    description: Operations related to URL shortening and redirection

paths:
  /url/shorten:
    post:
      tags:
        - URL Shortener
      summary: Create a shortened URL
      description: Accepts a long URL and optional metadata to create a shortened URL
      operationId: createShortUrl
      security:
        - bearerAuth: [ ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UrlShortenerDto'
      responses:
        '201':
          description: Shortened URL created successfully
          content:
            application/json:
              schema:
                type: string
                example: "https://yourdomain.com/u/abc123"
        '400':
          description: Invalid input data
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /url/redirect:
    get:
      tags:
        - URL Shortener
      summary: Redirect to long URL
      description: Accepts a shortened URL and redirects to the original long URL
      operationId: redirectToLongUrl
      parameters:
        - name: shortUrl
          in: query
          required: true
          description: The short URL key
          schema:
            type: string
            example: abc123
      responses:
        '302':
          description: Redirect to the original URL
        '404':
          description: Short URL not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    UrlShortenerDto:
      type: object
      required:
        - originalUrl
      properties:
        originalUrl:
          type: string
          format: uri
          description: Must start with "http://" or "https://"
          example: "https://example.com/resource"
        customAlias:
          type: boolean
          description: Whether the user requested a custom alias
        premiumUser:
          type: boolean
          description: Whether the user is premium
        highThroughput:
          type: boolean
          description: Indicates high request volume optimization
        needsDeterminism:
          type: boolean
          description: Indicates if the same URL should always return the same short URL
        internalTool:
          type: boolean
          description: Marks if used internally
        customAliasName:
          type: string
          maxLength: 30
          pattern: "^[a-zA-Z0-9_-]+$"
          description: Custom alias (max 30 characters, alphanumeric, - or _)
          example: "my_alias123"
        note:
          type: string
          maxLength: 255
          description: Optional note about the URL
        tags:
          type: array
          maxItems: 20
          description: List of tags (each max 30 characters)
          items:
            type: string
            maxLength: 30
        amountOfTime:
          type: integer
          format: int64
          description: It is amount of Time needed for Url to be Active after that it can be purged from the System
          example: 10
        unitTime:
          type: string
          enum: [ seconds, minutes, hours, Days, Months ]
          description: Unit of time associated with the amount
          example: "minutes"
