openapi: 3.0.3
info:
  title: URL Shortener API
  description: API for shortening URLs and retrieving original ones.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1/url
    description: Local server

paths:
  /shorten:
    post:
      summary: Create a shortened URL
      operationId: createShortUrl
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/CorrelationIdHeader'
        - $ref: '#/components/parameters/UserAgentHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UrlShortenerDto'
      responses:
        '201':
          description: Short URL created
          content:
            text/plain:
              schema:
                type: string
                example: http://short.ly/abc123
        '400':
          description: Invalid input
        '500':
          description: Server error

  /:
    get:
      summary: Redirect to the original URL
      operationId: redirectToLongUrl
      parameters:
        - $ref: '#/components/parameters/AuthorizationHeader'
        - $ref: '#/components/parameters/CorrelationIdHeader'
        - $ref: '#/components/parameters/UserAgentHeader'
        - name: shortUrl
          in: query
          required: true
          schema:
            type: string
          example: abc123
      responses:
        '302':
          description: Redirect to original URL
        '404':
          description: URL not found
        '500':
          description: Server error
components:
  parameters:
    AuthorizationHeader:
      name: Authorization
      in: header
      required: true
      schema:
        type: string
        example: Bearer <your_jwt_token>
      description: JWT access token

    CorrelationIdHeader:
      name: X-Correlation-ID
      in: header
      required: false
      schema:
        type: string
        example: 123e4567-e89b-12d3-a456-426614174000
      description: Correlation ID for tracing

    UserAgentHeader:
      name: User-Agent
      in: header
      required: false
      schema:
        type: string
        example: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
      description: Client's user agent string
  schemas:
    UrlShortenerDto:
      type: object
      required:
        - originalUrl
      properties:
        originalUrl:
          type: string
          example: https://example.com/very/long/url
        customAlias:
          type: boolean
        premiumUser:
          type: boolean
        highThroughput:
          type: boolean
        needsDeterminism:
          type: boolean
        internalTool:
          type: boolean
        customAliasName:
          type: string
          maxLength: 30
          pattern: '^[a-zA-Z0-9_-]+$'
          example: my-custom-alias
        note:
          type: string
          maxLength: 255
          example: For analytics
        tags:
          type: array
          items:
            type: string
          example: [ "analytics", "internal" ]

    UrlMapping:
      type: object
      properties:
        urlMappingId:
          type: integer
        originalUrl:
          type: string
        shortUrl:
          type: string
        userId:
          type: integer
        notes:
          type: string
        customAlias:
          type: boolean
        premiumUser:
          type: boolean
        highThroughput:
          type: boolean
        needsDeterminism:
          type: boolean
        internalTool:
          type: boolean
        customAliasName:
          type: string
        redirectType:
          type: integer
        tags:
          type: string
        strategy:
          type: string
        expiresAt:
          type: string
          format: date-time
        createdIp:
          type: string
        createdUserAgent:
          type: string
        isActive:
          type: boolean
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        updatedAt:
          type: string
          format: date-time
        updatedBy:
          type: string
